version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-dataguardsuite
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=uite-data-123-23444
      - MONGO_INITDB_DATABASE=dataguardsuite
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mongo-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  mongo-data:

networks:
  mongo-network:
